server:
  port: 8761
eureka:
  instance:
    hostname: springboot-06-springcloud-eureka #eureka实例的主机名
  client:
    register-with-eureka: false  #不将自己注册到eureka中
    fetch-registry: false  #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/